#if PLATFORM
using ShinyKmlRecorder.Services.Impl;

namespace ShinyKmlRecorder;


public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp
            .CreateBuilder()
            .UseMauiApp<App>()
            .UseShiny()
            .UseShinyShell(x => x.AddGeneratedMaps())
#if !DEBUG
            .UseSentry(x => x.Dsn = AssemblyInfo.SentryDsn)
#endif
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

#if ANDROID
        // required for sqlite android 16kb fix
        SQLitePCL.Batteries_V2.Init();
#endif
#if DEBUG
        builder.Logging.SetMinimumLevel(LogLevel.Trace);
        builder.Logging.AddDebug();
#endif
        builder.Services.AddSingleton(AppInfo.Current);
        builder.Services.AddSingleton(Battery.Default);
        builder.Services.AddSingleton(TimeProvider.System);
        
        builder.Services.AddShinyService<LogService>();
        builder.Services.AddGps<ShinyKmlRecorder.Delegates.MyGpsDelegate>();

        // this is source generated by Shiny.Extensions.DependencyInjection - simply add [Singleton], [Scoped], or [Transient] to your classes
        builder.Services.AddGeneratedServices();
        var app = builder.Build();

        return app;
    }
}
#endif