#if PLATFORM
using System.Text.Json.Serialization;
using Shiny.DocumentDb;
using Shiny.DocumentDb.Sqlite;
using ShinyKmlRecorder.Services.Impl;

namespace ShinyKmlRecorder;


public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp
            .CreateBuilder()
            .UseMauiApp<App>()
            .UseShiny()
            .UseShinyShell(x => x.AddGeneratedMaps())
            .UseMauiMaps()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });
        
        builder.Services.AddDocumentStore(opts =>
        {
            var dbPath = Path.Combine(FileSystem.AppDataDirectory, "app.db");
            opts.DatabaseProvider = new SqliteDatabaseProvider($"Data Source={dbPath}");
            opts.JsonSerializerOptions = AppJsonContext.Default.Options;
            opts.UseReflectionFallback = false;
#if DEBUG
            opts.Logging = sql => System.Diagnostics.Debug.WriteLine("SQLite Query: " + sql);
#endif
        });

#if DEBUG
        builder.Logging.SetMinimumLevel(LogLevel.Trace);
        builder.Logging.AddDebug();
#endif
        builder.Services.AddSingleton(AppInfo.Current);
        builder.Services.AddSingleton(Battery.Default);
        builder.Services.AddSingleton(TimeProvider.System);
        
        builder.Services.AddShinyService<LogService>();
        builder.Services.AddGps<ShinyKmlRecorder.Delegates.MyGpsDelegate>();

        // this is source generated by Shiny.Extensions.DependencyInjection - simply add [Singleton], [Scoped], or [Transient] to your classes
        builder.Services.AddGeneratedServices();
        var app = builder.Build();

        return app;
    }
}
#endif


[JsonSerializable(typeof(LogRecord))]
public partial class AppJsonContext : JsonSerializerContext;